### ISSUE TITLE
How to evalutate on the test data for novel dataset?

### ISSUE THREAD

**Issue by LuketheDukeBates** [rrmenon10/ADAPET#23]
Thanks for the great repo! two quick questions I am hoping you can help me with.
1) How do I evalutate on the test data for a novel dataset?
2) I do not believe multilabel classification is supported, is that correct?

Thanks so much!

**Comment by rrmenon10** [comment]
Glad you like our repo, @LuketheDukeBates! Regarding the novel dataset evaluation, first I hope that you've trained the models using the instruction provided [here](https://github.com/rrmenon10/ADAPET#train-your-own-adapet). Once you have done this, you should be able to run an evaluation using the command `python src/test.py -e exp_dir={trained_model_dir}.` So long as the test dataset is placed in the same directory as the train dataset, things should work out fine, if not, feel free to respond to this issue and I can take another look at it.

2. Could you define what you mean by multilabel classification here? If it is classes with multiple tokens, technically we do since ReCoRD and WSC have tokens with multiple labels in them.

**Comment by LuketheDukeBates** [comment]
Thank you so much for the response @rrmenon10!
What I mean is what if I have data that could be one class or multiple classes at once?
For example:
I like an animal that meows. This person could be talking about a _ [LBL] = 'cat'
I like an animal that barks. This person could be talking about a _  [LBL] = 'dog'
I like an animal that tweets. This person could be talking about a _  [LBL] = 'bird'
I like an animal with fur. This person could be talking about a _ [LBL_1] = 'dog', [LBL_2] = 'cat'
I like an animal that can be a pet. This person could be talking about a _ [LBL_1] = 'dog', [LBL_2] = 'cat', [LBL_3] = 'bird'

A more realistic dataset would be something like this: https://github.com/tianqwang/Toxic-Comment-Classification-Challenge

Thanks!

**Comment by rrmenon10** [comment]
Thanks for the clarification. We do not handle these classification tasks in our codebase.
