### ISSUE TITLE
Trained model not saved

### ISSUE THREAD

**Issue by xq2187** [rrmenon10/ADAPET#36]
Hi @rrmenon10,

Thank you so much for sharing the code for ADAPET! This is very helpful. I've tried to train my own ADAPET using your sample code, and looks like it succeed with the message: "Finished 1 batches" (there is only 1 batch here probably because I used only a few (~10) examples in the training set, but I'm not completely sure). But I could not find the trained model anywhere in the exp_out/generic/albert-xxlarge-v2/{timestamp} folder. Do you have any thoughts or comments here? Thanks a lot!

**Comment by rrmenon10** [comment]
Hi @xq2187, if you're configuration file is still [generic.json](https://github.com/rrmenon10/ADAPET/blob/master/config/Generic.json), it should have run training for 1000 batches since num_batches=1000. Also, it would have saved 4 checkpoints since eval_every=250, i.e., it will save a model once every 250 batches. If you have modified the configuration file for your specific task, these values may look different, so the model may not have been saved. You could check if num_batches==eval_every in your configuration.
